title: The `eigen` Layers
author: Rohan
baseurl: "/volog"
description: "Brain dump."
profile_url: "https://crohan009.github.io/"
github_username:  crohan009

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
